name: code_style

on: [push]
jobs:
  code_style:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install astyle
        run: |
          sudo apt-get install -y astyle
      - run: ./astyle_check_all.sh

      - name: Install cpplint
        run: |
          sudo apt-get install python3-pip -y               \
          && pip3 install --upgrade setuptools              \
          && sudo pip3 install cpplint
      - run: chmod +x cpplint.sh && ./cpplint.sh
